## Reti Ricorrenti

In [ ]:
vedi appunti

### LSTM
long short term memory

In [5]:
import keras.layers as layers
import tensorflow as tf

In [4]:
gru_layer = layers.GRU(units = 128) # units: dimensione dell'Hidden State, quanto è grande la memoria interna, non  il numero di celle? forse è la stessa cosa
# vettore con 128 numeri

In [ ]:
# Tensore di input allo strato ricorrente
# BATCH_SIZE x SEQUENCE_LENGTH x EMBEDDING_DIM
# quante frasi, len max di una frase, numero di feature di ciascuno elemento della seq. frase

ciascuno elemento della seq è un vettore di len embedding dim

# Maschera
nello stesso batch, ci sono diverse sequenze (ex. frasi), ciascuna frase ha sua lunghezza. 
seq_length deve essere la len della frase più lunga, quell più corte devono ess. riempite con padding 
(ex. zeri, devo dire a keras che non portano informazione, concetto di maschera)

In [8]:
# BATCH_SIZE x SEQUENCE_LENGTH x EMBEDDING_DIM
x_batch = tf.random.normal( [32, 30, 10])

In [9]:
y = gru_layer(x_batch)

In [11]:
y # restituisce l'ultimo hidden state (composto dalle 32 elaborazioni precedenti)

<tf.Tensor: shape=(32, 128), dtype=float32, numpy=
array([[-0.01431752, -0.2581449 , -0.03054796, ...,  0.22711878,
        -0.2937552 ,  0.03248591],
       [ 0.20853296, -0.11045919, -0.11806302, ...,  0.24363665,
        -0.24423325, -0.23218131],
       [ 0.00972743, -0.1041273 ,  0.03437356, ...,  0.09452583,
        -0.00869979, -0.0696394 ],
       ...,
       [-0.1041753 , -0.11133437, -0.03490374, ..., -0.06892341,
         0.03977083, -0.01559643],
       [-0.0864511 , -0.10995473,  0.18583956, ...,  0.15422367,
        -0.15543689,  0.04096818],
       [-0.18974349, -0.16449638, -0.19645408, ...,  0.06310724,
        -0.17992799, -0.02642601]], dtype=float32)>

In [12]:
# per restituire tutti gli hidden state (tutti gli h_i)
gru_layer = layers.GRU(units = 128, return_sequences=True) # units: dimensione dell'Hidden State, quanto è grande la memoria interna
x_batch = tf.random.normal( [32, 30, 10])
y = gru_layer(x_batch)
y

<tf.Tensor: shape=(32, 30, 128), dtype=float32, numpy=
array([[[-8.20177197e-02,  4.45691682e-02, -4.54269350e-02, ...,
         -1.34359738e-02,  4.73987162e-02,  2.96419226e-02],
        [-1.05811968e-01,  8.41898322e-02, -8.76795053e-02, ...,
          1.00578330e-02, -1.11714832e-01, -1.32657951e-02],
        [ 6.32366166e-02, -6.02614358e-02, -2.88195834e-02, ...,
         -4.42120321e-02,  2.20518932e-02,  2.82523446e-02],
        ...,
        [-1.70123890e-01, -1.11861184e-01, -8.17061365e-02, ...,
         -1.42402723e-01,  1.53807625e-01, -1.04253985e-01],
        [-9.72051919e-03, -2.89393097e-01, -6.63118586e-02, ...,
         -1.00183114e-01,  2.85009980e-01,  1.03299849e-01],
        [-1.09267004e-01, -3.18161011e-01,  1.37419775e-01, ...,
          8.91855955e-02,  1.96489543e-01, -8.64438713e-02]],

       [[ 9.16533172e-02, -4.78549860e-02, -5.64067625e-02, ...,
          7.26659745e-02, -1.51029381e-04,  1.81525841e-01],
        [ 6.87808916e-02,  7.55352229e-02, -1.48

In [ ]:
# Note
Dimensioni di y: 32 (batch) 
                x 30 (per ogni batch voglio tutti gli hidden state, ovvero elaborazione per ogni elemento della seq o frase) 
                x 128 (numero di unità, units): dimensione di ogni hidden state

#### Rete Ricorrente Profonda

In [13]:
# Gli strati ricorrenti possono essere messi uno sull'altro

In [ ]:
# vedi appunti

### Esercizio Machine Translation
dataset: manythings machine translation: https://www.manythings.org/anki/

In [17]:
import spacy

In [19]:
!python -m spacy download en_core_web_md
!python -m spacy download it_core_news_md

2023-09-12 11:16:43.050265: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-12 11:16:45.093770: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 MB 13.7 MB/s eta 0:00:0000:0100:01
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
2023-09-12 11:17:07.677949: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-12 11:17:09.355872: W tensorflow/compiler/tf2tensorr

In [14]:
!wget https://www.manythings.org/anki/ita-eng.zip # frasi separate da tab

--2023-09-12 11:06:28--  https://www.manythings.org/anki/ita-eng.zip
Resolving www.manythings.org (www.manythings.org)... 173.254.30.110, 162.159.24.49, 162.159.25.241
Connecting to www.manythings.org (www.manythings.org)|173.254.30.110|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8220355 (7.8M) [application/zip]
Saving to: ‘ita-eng.zip’

ita-eng.zip         100%[===================>]   7.84M  1.10MB/s    in 8.7s    

2023-09-12 11:06:38 (924 KB/s) - ‘ita-eng.zip’ saved [8220355/8220355]



In [15]:
!unzip ita-eng.zip

Archive:  ita-eng.zip
  inflating: ita.txt                 
  inflating: _about.txt              


#### Tokenizzazione

In [16]:
# ex. le 10k parole più frequenti

In [25]:
class Tokenizer:
    def __init__(self, language):
        self.language = language
        
        if language == "it":
            self.nlp = spacy.load("it_core_news_md")
        else:
            self.nlp = spacy.load("en_core_web_md")

    def tokenize(self, text):
        return [token.text.lower() for token in self.nlp(text)] # perché token.text?

In [26]:
Tokenizer("it").tokenize("oggi non ci va di fare molto")

['oggi', 'non', 'ci', 'va', 'di', 'fare', 'molto']

#### Vocabolario
build dictionary che associa un numero intero a ogni parola

In [41]:
from tqdm import tqdm
from collections import Counter # frequenza di oggetti presenti in una lista; buildable dinamicamente con Update

In [34]:
c = Counter()
c.update(["and", "is", "and"])
c

Counter({'and': 2, 'is': 1})

In [46]:
def build_vaocabularies(filepath, num_rows, vocab_size):
    # counter
    en_counter = Counter()
    it_counter = Counter()
    # tokenizzatori
    en_tokenizer = Tokenizer("en")
    it_tokenizer = Tokenizer("it")

    # vocabolari
    en_vocab = {"<PAD>": 0, "<UNK>": 1, "<BOS>": 2, "<EOS>": 3}
    it_vocab = {"<PAD>": 0, "<UNK>": 1, "<BOS>": 2, "<EOS>": 3}
    #  PAD ci serve per il Padding, token speciale
    # UNK, unknown, il dict è limitato, le parole rare non saranno rappresentate (le tokenizzazione più sofisticate non hanno vocabolario limitato)
    # BOS, begin of sentence, per dire alla rete "traduci questo: ..."
    # EOS, end of sentence
    counter = 0
    pbar = tqdm()
    with open(filepath, "r") as f:
        while (line := f.readline() ) is not None: 
        # il tricheco := assegnamento con espressione (a = 3 è una istruzione, a + 3 è espressione perché ritorna a). a=(b=3) non va in Python
        #      walrus: assegnamento che ritorna il suo valore: leggi la linea, assegna a line, la ritorna e se non è None va avanti (c=(d:=2) funge)

            # splitta riga in base ai tab
            en_sentence, it_sentence, *_ = line.split("\t") # *_ prende qualcosa (la fonte della frase nel dataset) e lo ignora
            # token
            en_tokenized = en_tokenizer.tokenize(en_sentence)
            it_tokenized = it_tokenizer.tokenize(it_sentence)
            # update dei Counter
            en_counter.update(en_tokenized)
            it_counter.update(it_tokenized)

            pbar.update(1) # l'incremento del counter

            # per leggere solo tot righe
            counter += 1
            if num_rows and counter >= num_rows:
                break
    
    # update dizionari
    most_common_en = [item[0] for item in en_counter.most_common(vocab_size)] # il primo elemento delle most_common
    most_common_it = [item[0] for item in it_counter.most_common(vocab_size)]

    en_vocab |= {word: idx for idx, word in enumerate(most_common_en, start = 4)} # |= update dizionario; start=4 perché fino al 3 sono special tokens
    it_vocab |= {word: idx for idx, word in enumerate(most_common_it, start = 4)}
    # dizionari inversi
    en_vocab_inv = {idx: word for word, idx in en_vocab.items()}
    it_vocab_inv = {idx: word for word, idx in it_vocab.items()} 

    return en_vocab, en_vocab_inv, it_vocab, it_vocab_inv

In [47]:
# update dizionario, sintassi python ultime versioni
a = {1: 2}
a |= {2:3, 3:4}

In [51]:
# prova su poche righe
en_vocab, en_vocab_inv, it_vocab, it_vocab_inv = \
build_vaocabularies(filepath="ita.txt", num_rows=60, vocab_size=10_000)



0it [00:00, ?it/s]

6it [00:00, 52.04it/s]

12it [00:00, 50.20it/s]

18it [00:00, 50.17it/s]

24it [00:00, 50.23it/s]

30it [00:00, 40.81it/s]

35it [00:00, 40.16it/s]

40it [00:00, 41.55it/s]

45it [00:01, 43.43it/s]

50it [00:01, 44.88it/s]

55it [00:01, 39.78it/s]

60it [00:01, 41.31it/s]


In [52]:
en_vocab

{'<PAD>': 0,
 '<UNK>': 1,
 '<BOS>': 2,
 '<EOS>': 3,
 '.': 4,
 '!': 5,
 'stay': 6,
 'duck': 7,
 'jump': 8,
 'wait': 9,
 'do': 10,
 'it': 11,
 'go': 12,
 'on': 13,
 'stop': 14,
 'hello': 15,
 'i': 16,
 'run': 17,
 'hid': 18,
 'hi': 19,
 'who': 20,
 '?': 21,
 'wow': 22,
 'ran': 23}

In [53]:
it_vocab_inv

{0: '<PAD>',
 1: '<UNK>',
 2: '<BOS>',
 3: '<EOS>',
 4: '.',
 5: '!',
 6: 'ciao',
 7: 'si',
 8: 'avanti',
 9: 'mi',
 10: 'salta',
 11: 'salti',
 12: 'saltate',
 13: 'aspetta',
 14: 'aspettate',
 15: 'aspetti',
 16: 'faccia',
 17: 'sono',
 18: 'corri',
 19: 'corra',
 20: 'correte',
 21: 'chi',
 22: '?',
 23: 'wow',
 24: 'amore',
 25: 'tesoro',
 26: 'immergiti',
 27: 'immerga',
 28: 'immergetevi',
 29: 'tuffati',
 30: 'tuffi',
 31: 'tuffatevi',
 32: 'resta',
 33: 'stai',
 34: 'stia',
 35: 'state',
 36: 'resti',
 37: 'restate',
 38: 'rimani',
 39: 'rimanga',
 40: 'rimanete',
 41: 'fermati',
 42: 'fermatevi',
 43: 'stop',
 44: 'fermi',
 45: 'fallo',
 46: 'falla',
 47: 'lo',
 48: 'la',
 49: 'fatelo',
 50: 'fatela',
 51: 'vai',
 52: 'continua',
 53: 'continui',
 54: 'continuate',
 55: 'vada',
 56: 'andate',
 57: 'buongiorno',
 58: 'salve',
 59: 'nascosto',
 60: 'nascosta',
 61: 'nascosi',
 62: 'ho',
 63: 'corso'}

In [54]:
# ora su 60_000
en_vocab, en_vocab_inv, it_vocab, it_vocab_inv = \
build_vaocabularies(filepath="ita.txt", num_rows=60_000, vocab_size=10_000)



0it [00:00, ?it/s]

4it [00:00, 37.03it/s]

8it [00:00, 37.23it/s]

13it [00:00, 40.67it/s]

18it [00:00, 41.75it/s]

23it [00:00, 42.57it/s]

28it [00:00, 43.76it/s]

33it [00:00, 44.59it/s]

38it [00:00, 39.83it/s]

43it [00:01, 40.39it/s]

48it [00:01, 41.65it/s]

53it [00:01, 41.58it/s]

58it [00:01, 40.17it/s]

63it [00:01, 38.70it/s]

67it [00:01, 37.92it/s]

71it [00:01, 38.06it/s]

76it [00:01, 39.29it/s]

81it [00:01, 41.96it/s]

86it [00:02, 40.35it/s]

91it [00:02, 42.74it/s]

97it [00:02, 45.69it/s]

103it [00:02, 47.57it/s]

108it [00:02, 47.85it/s]

113it [00:02, 46.80it/s]

118it [00:02, 45.73it/s]

123it [00:02, 43.29it/s]

128it [00:03, 44.45it/s]

133it [00:03, 44.77it/s]

138it [00:03, 43.67it/s]

143it [00:03, 41.08it/s]

148it [00:03, 40.67it/s]

153it [00:03, 42.78it/s]

159it [00:03, 45.44it/s]

164it [00:03, 43.70it/s]

169it [00:03, 41.97it/s]

174it [00:04, 40.92it/s]

179it [00:04, 42.26it/s]

184it [00:04, 42.83it/s]

189it [00:04, 43.60it/s]

194it [00:04

In [ ]:
Note:
Any sistema di NLP: tokenizzazione, costruzione dizionario

#### Split train-validation-test

In [58]:
import random

In [61]:
def split_file(filepath):
    with open(filepath, "r") as f:
        lines = [line[:-1] for line in f.readlines()] #line[:-1] per non prednere il ritorno a capo
    num_rows = len(lines)
    # split random
    shuffled_rows_idxs = random.sample( list( range(num_rows)), k = num_rows) # shuffle
    
    train_idxs = shuffled_rows_idxs[:int( num_rows*0.6)] # 60%
    val_idxs = shuffled_rows_idxs[int( num_rows*0.6) : int( num_rows*0.8)] # 20%
    test_idxs = shuffled_rows_idxs[int( num_rows*0.8) :] # 20%

    # train
    with open("train.txt", "w") as f:
        f.writelines( [lines[idx] for idx in train_idxs] )
    # val
    with open("val.txt", "w") as f:
        f.writelines( [lines[idx] for idx in val_idxs] )
    # test
    with open("test.txt", "w") as f:
        f.writelines( [lines[idx] for idx in test_idxs] )

In [62]:
split_file("ita.txt")
# unix e windows trattano diversamento il ritorno a capo

#### Dataset
let's build it: vedi appunti

In [66]:
UNK = "<UNK>"
BOS = "<BOS>"
EOS = "<EOS>"
PAD = "<PAD>"

In [65]:
# funzione (in realtà un generatore) che codifica i sample, in numeri interi
# cerca generatore Python

In [123]:
"""
def dataset_generator(filepath, en_dict, it_dict, en_tokenizer, it_tokenizer):
    def gen():
        with open(filepath, "r") as f:
            while (line := f.readline()) is not None: #finchè ci sono linee
                en_sentence, it_sentence, *_ = line.split("\t")
                en_sentence_tokenized = en_tokenizer.tokenize(en_sentence)
                it_sentence_tokenized = it_tokenizer.tokenize(it_sentence)
    
                # add special tokens
                src_sentence_tokenized = en_sentence_tokenized + [EOS]
                tgt_sentence_in_tokenized = [BOS] + it_sentence_tokenized # target in
                tgt_sentence_out_tokenized = it_sentence_tokenized.copy() + [EOS] # target out ##.copy() non serviva
    
                # finora sono lista di stringhe
                # conversione nei corrispondenti indici
                src_sentence_encoded = [en_dict.get(token, en_dict[UNK]) for token in src_sentence_tokenized] # la get non va in eccezione se non trova la chiave (token)
                tgt_sentence_in_encoded = [it_dict.get(token, en_dict[UNK]) for token in tgt_sentence_in_tokenized]
                tgt_sentence_out_encoded = [it_dict.get(token, en_dict[UNK]) for token in tgt_sentence_out_tokenized]
    
                yield (src_sentence_encoded, tgt_sentence_in_encoded), tgt_sentence_out_encoded # input (src e tgt_in), output: tgt_out
    return gen
"""
def dataset_generator(filepath, en_dict, it_dict, en_tokenizer, it_tokenizer):
    def gen():
        with open(filepath, "r") as f:
            while (line := f.readline()) is not None: #finchè ci sono linee
                en_sentence, it_sentence, *_ = line.split("\t")
                en_sentence_tokenized = en_tokenizer.tokenize(en_sentence)
                it_sentence_tokenized = it_tokenizer.tokenize(it_sentence)
                
                # add special tokens
                src_sentence_tokenized = en_sentence_tokenized + [EOS]
                tgt_sentence_in_tokenized = [BOS] + it_sentence_tokenized # target in
                tgt_sentence_out_tokenized = it_sentence_tokenized.copy() + [EOS]  # target out ##.copy() non serviva
                
                # finora sono lista di stringhe
                # conversione nei corrispondenti indici
                src_sentence_encoded = [en_dict.get(token, en_dict[UNK]) for token in src_sentence_tokenized] # la get non va in eccezione se non trova la chiave (token)
                tgt_sentence_in_encoded = [it_dict.get(token, it_dict[UNK]) for token in tgt_sentence_in_tokenized]
                tgt_sentence_out_encoded = [it_dict.get(token, it_dict[UNK]) for token in tgt_sentence_out_tokenized]

                yield (src_sentence_encoded, tgt_sentence_in_encoded), tgt_sentence_out_encoded # input (src e tgt_in), output: tgt_out

    return gen
# un generatore si comporta come una lista (itaratore), posso ciclare su yield. Come se stessi consumando una lista
# quando arriva a yield la funzione da un output, come il return ma non termina la funzione

In [68]:
# Prova
"""
for (src, tgt_in), tgt_out in dataset_generator(
    "val.txt", 
    en_vocab, 
    it_vocab,
    Tokenizer("en"), Tokenizer("it")):
    
    print(src)
    print(tgt_in)
    print(tgt_out)
    break
"""

[5, 13, 122, 119, 33, 1, 4, 3]
[2, 8, 344, 126, 663, 1, 4]
[8, 344, 126, 663, 1, 4, 3]


In [124]:
from tensorflow.data import Dataset
import tensorflow as tf

In [125]:
trainset = Dataset.from_generator(
    generator = dataset_generator("train.txt", en_vocab, it_vocab, Tokenizer("en"), Tokenizer("it")),
    output_signature = (
        (tf.TensorSpec(shape=(None,), dtype=tf.int32), # shape = None sta per: c'è una dimensione, di len arbitraria
         tf.TensorSpec(shape=(None,), dtype=tf.int32)),
            tf.TensorSpec(shape=(None,), dtype=tf.int32)
    )
)

In [126]:
# per vedere se funge
for data in trainset:
    x = data
    break

2023-09-12 17:32:14.989887: W tensorflow/core/framework/op_kernel.cc:1816] INVALID_ARGUMENT: ValueError: not enough values to unpack (expected at least 2, got 1)
Traceback (most recent call last):

  File "/home/naska/miniconda3/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 268, in __call__
    ret = func(*args)

  File "/home/naska/miniconda3/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 643, in wrapper
    return func(*args, **kwargs)

  File "/home/naska/miniconda3/lib/python3.9/site-packages/tensorflow/python/data/ops/from_generator_op.py", line 198, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/tmp/ipykernel_26407/1231811761.py", line 28, in gen
    en_sentence, it_sentence, *_ = line.split("\t")

ValueError: not enough values to unpack (expected at least 2, got 1)




In [83]:
x[0]

(<tf.Tensor: shape=(6,), dtype=int32, numpy=array([4343,    5,   34,   69,    4,    3], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([  2, 678,  48, 145,   4], dtype=int32)>)

In [88]:
trainset = Dataset.from_generator(
    generator=dataset_generator("train.txt", en_vocab, it_vocab, Tokenizer("en"), Tokenizer("it")),
    output_signature=(
        (tf.TensorSpec(shape=(None,), dtype=tf.int32), tf.TensorSpec(shape=(None,), dtype=tf.int32)),
        tf.TensorSpec(shape=(None,), dtype=tf.int32))
)

valset = Dataset.from_generator(
    generator=dataset_generator("val.txt", en_vocab, it_vocab, Tokenizer("en"), Tokenizer("it")),
    output_signature=(
        (tf.TensorSpec(shape=(None,), dtype=tf.int32), tf.TensorSpec(shape=(None,), dtype=tf.int32)),
        tf.TensorSpec(shape=(None,), dtype=tf.int32))
)

testset = Dataset.from_generator(
    generator=dataset_generator("test.txt", en_vocab, it_vocab, Tokenizer("en"), Tokenizer("it")),
    output_signature=(
        (tf.TensorSpec(shape=(None,), dtype=tf.int32), tf.TensorSpec(shape=(None,), dtype=tf.int32)),
        tf.TensorSpec(shape=(None,), dtype=tf.int32))
)

In [89]:
trainset = trainset.shuffle(buffer_size=10_000, reshuffle_each_iteration=True)
trainset = trainset.batch(batch_size=32)

In [90]:
for data in trainset:
    x = data
    break

2023-09-12 15:06:04.980891: W tensorflow/core/framework/op_kernel.cc:1816] INVALID_ARGUMENT: ValueError: not enough values to unpack (expected at least 2, got 1)
Traceback (most recent call last):

  File "/home/naska/miniconda3/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 268, in __call__
    ret = func(*args)

  File "/home/naska/miniconda3/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 643, in wrapper
    return func(*args, **kwargs)

  File "/home/naska/miniconda3/lib/python3.9/site-packages/tensorflow/python/data/ops/from_generator_op.py", line 198, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/tmp/ipykernel_26407/195809842.py", line 5, in gen
    en_sentence, it_sentence, *_ = line.split("\t")

ValueError: not enough values to unpack (expected at least 2, got 1)




InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_3_device_/job:localhost/replica:0/task:0/device:CPU:0}} ValueError: not enough values to unpack (expected at least 2, got 1)
Traceback (most recent call last):

  File "/home/naska/miniconda3/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 268, in __call__
    ret = func(*args)

  File "/home/naska/miniconda3/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 643, in wrapper
    return func(*args, **kwargs)

  File "/home/naska/miniconda3/lib/python3.9/site-packages/tensorflow/python/data/ops/from_generator_op.py", line 198, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/tmp/ipykernel_26407/195809842.py", line 5, in gen
    en_sentence, it_sentence, *_ = line.split("\t")

ValueError: not enough values to unpack (expected at least 2, got 1)


	 [[{{node PyFunc}}]] [Op:IteratorGetNext] name: 

In [ ]:
x[0][0].shape
x[0][1].shape

#### Modello Encoder Decoder

In [ ]:
# vedi appunti x teoria Encoder-Decoder

In [102]:
import keras

In [105]:
from keras.layers import Embedding, GRUCell

In [106]:
embedding_layer = Embedding(input_dim = 10_000, output_dim=100, mask_zero=True) # mask_zero è padding

In [107]:
output = embedding_layer(tf.constant([[1, 1, 2, 5, 0, 0], [5, 3, 5, 5, 0, 0]], dtype=tf.int32))

In [108]:
embedding_layer.get_weights()[0].shape

(10000, 100)

In [109]:
output._keras_mask

<tf.Tensor: shape=(2, 6), dtype=bool, numpy=
array([[ True,  True,  True,  True, False, False],
       [ True,  True,  True,  True, False, False]])>

In [110]:
"""
MAX_SENTENCE_LENGTH = 100

class GenerativeCallback(keras.callbacks.Callback):
    def __init__(self, src_dictionary_inv, dst_dictionary_inv, dataset, max_length):
        super().__init__()
        self.src_dictionary_inv = src_dictionary_inv
        self.dst_dictionary_inv = dst_dictionary_inv
        self.dataset = dataset
        self.max_length = max_length

    def on_epoch_end(self, epoch, logs=None):

        # extract random batch from dataset
        batch_idx = random.randrange(0, len(self.dataset))

        (batch, batch_lengths, _, _), _ = self.dataset[batch_idx]

        output = self.model((batch, batch_lengths), training=False, max_sentence_length=MAX_SENTENCE_LENGTH)

        for src_sentence, dst_sentence in zip(batch, output):
            print("src sentence:")
            for idx in np.array(src_sentence):
                if idx == EOS_IDX:
                    break
                print(self.src_dictionary_inv[idx], end = " ")
            print("\n")
            print("dst sentence:")
            for idx in np.array(dst_sentence):
                if idx == EOS_IDX:
                    break
                print(self.dst_dictionary_inv[idx], end = " ")
            print("\n")

In [111]:
# Encoder: vede sentence da tradurre (termina con <EOS>)

In [115]:
class Encoder(keras.Model):
    def __init__(self, vocabulary_size, embedding_size, recurrent_layers, recurrent_units, **kwargs):
        """
        args
        ----
        - vocabulary_size (int): including special tokens (<BOS>, <EOS>, <UNK>)
        - embedding_size (int): dimensione dello spazio degli embedding

        """
        super().__init__(**kwargs)

        # embedding
        # 0 index mean padding
        self.embedding = Embedding(
            vocabulary_size, embedding_size, mask_zero=True)

        gru_cells = [GRUCell(recurrent_units) for _ in range(recurrent_layers)]

        stacked_cells = tf.keras.layers.StackedRNNCells(gru_cells)
        self.gru_layer = tf.keras.layers.RNN(stacked_cells, return_state=True)

    def call(self, data, training=None):
        x = self.embedding(data, training=training)
        output, *state = self.gru_layer(x, training=training)

        return output, state

In [116]:
class Decoder(keras.Model):
    def __init__(self, vocabulary_size, embedding_size, recurrent_layers, recurrent_units, **kwargs):
        super().__init__(**kwargs)

        self.recurrent_layers = recurrent_layers
        self.recurrent_units = recurrent_units

        self.embedding = Embedding(
            vocabulary_size, embedding_size, mask_zero=True)

        gru_cells = [GRUCell(recurrent_units) for _ in range(recurrent_layers)]

        stacked_cells = tf.keras.layers.StackedRNNCells(gru_cells)
        self.gru_layer = tf.keras.layers.RNN(stacked_cells, return_sequences=True, return_state=True)

        self.dense = tf.keras.layers.Dense(vocabulary_size)

    def call(self, data, encoder_output, encoder_state, training=None, max_sentence_length=None):
        # data.shape = batch x length
        # initial_state.shape = batch x recurrent_layers x recurrent_units
        # encoder_output.shape = batch x length x recurrent_units

        if data is not None:
            # Addestramento
            x = self.embedding(data, training=training)
            # data.shape = batch x length x embedding
            # concatena il contesto con l'input
            # x = tf.concat([x, tf.repeat(tf.expand_dims(encoder_output[:, -1, :], axis=1), repeats=x.shape[1], axis=1)], axis=2)

            output, *state = self.gru_layer(x, training=training, initial_state=encoder_state)
            return tf.keras.activations.softmax(self.dense(output)), state
        else:
            # Generazione
            batch_size = encoder_output.shape[0]
            x = tf.fill([batch_size, 1], BOS)
            state = encoder_state
            out_words_list = []
            for _ in range(max_sentence_length):
                # x.shape = batch_size x 1 x embedding_size
                x = self.embedding(x, training=training)
                # aggiunge il contesto
                # x = tf.concat([x, tf.expand_dims(encoder_output[:, -1, :], axis=1)], axis=2)
                output, *state = self.gru_layer(x, training=training, initial_state=state)
                # output_size = batch_size x 1 x embedding_size

                # trova i caratteri più probabili
                # probs.shape = batch_size x vocabulary_size
                probs = tf.keras.activations.softmax(self.dense(tf.squeeze(output)))
                x = tf.expand_dims(tf.argmax(probs, axis=1), axis=1)
                out_words_list.append(x)

            return tf.concat(out_words_list, axis=1), state

In [117]:
MAX_SENTENCE_LENGTH = 20

In [118]:
class EncoderDecoder(keras.Model):
    def __init__(self, vocabulary_size, embedding_size, recurrent_layers, recurrent_units, **kwargs):
        super().__init__(**kwargs)

        self.vocabulary_size = vocabulary_size
        self.embedding_size = embedding_size
        self.recurrent_layers = recurrent_layers
        self.recurrent_units = recurrent_units


        self.encoder = Encoder(vocabulary_size, embedding_size,
                               recurrent_layers, recurrent_units)
        self.decoder = Decoder(vocabulary_size, embedding_size, recurrent_layers,
                               recurrent_units)


    def call(self, data, training=None, max_sentence_length=MAX_SENTENCE_LENGTH):
        # unpack data
        if len(data) == 2:
            src_sentences, dst_sentences = data
        else:
            src_sentences = data
            dst_sentences = None

        # encoder call
        # encoder_output.shape = batch x len_sentences x encoder_recurrent_units
        encoder_output, encoder_state = self.encoder(src_sentences, training=training)

        decoder_output, decoder_state = self.decoder(dst_sentences, encoder_output, encoder_state, training=training, max_sentence_length=MAX_SENTENCE_LENGTH)

        return decoder_output

In [119]:
def custom_loss(y_true, y_pred):
    y_true_reshaped = tf.reshape(y_true, [-1])
    y_pred_reshaped = tf.reshape(y_pred, [-1, y_pred.shape[-1]])
    scc = tf.keras.losses.SparseCategoricalCrossentropy(
        reduction=tf.keras.losses.Reduction.NONE)
    results = scc(y_true_reshaped, y_pred_reshaped)
    mask = tf.cast(y_true_reshaped != 0, tf.float32)
    return tf.reduce_sum(results*mask) / tf.reduce_sum(mask)

#### Addestramento

In [120]:
encoder_decoder = EncoderDecoder(vocabulary_size=10_000+4, embedding_size=256, recurrent_layers=2, recurrent_units=256)

In [121]:
encoder_decoder.compile(optimizer=keras.optimizers.Adam(), loss=custom_loss)

In [122]:
encoder_decoder.fit(x=trainset, steps_per_epoch=100, epochs=10)

Epoch 1/10


2023-09-12 17:28:37.606042: W tensorflow/core/framework/op_kernel.cc:1816] INVALID_ARGUMENT: ValueError: not enough values to unpack (expected at least 2, got 1)
Traceback (most recent call last):

  File "/home/naska/miniconda3/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 268, in __call__
    ret = func(*args)

  File "/home/naska/miniconda3/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 643, in wrapper
    return func(*args, **kwargs)

  File "/home/naska/miniconda3/lib/python3.9/site-packages/tensorflow/python/data/ops/from_generator_op.py", line 198, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/tmp/ipykernel_26407/195809842.py", line 5, in gen
    en_sentence, it_sentence, *_ = line.split("\t")

ValueError: not enough values to unpack (expected at least 2, got 1)




InvalidArgumentError: Graph execution error:

ValueError: not enough values to unpack (expected at least 2, got 1)
Traceback (most recent call last):

  File "/home/naska/miniconda3/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 268, in __call__
    ret = func(*args)

  File "/home/naska/miniconda3/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 643, in wrapper
    return func(*args, **kwargs)

  File "/home/naska/miniconda3/lib/python3.9/site-packages/tensorflow/python/data/ops/from_generator_op.py", line 198, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/tmp/ipykernel_26407/195809842.py", line 5, in gen
    en_sentence, it_sentence, *_ = line.split("\t")

ValueError: not enough values to unpack (expected at least 2, got 1)


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_9876]

In [ ]:
# vedi file prof.